additionalArguments:
  - "--accesslog=true"
  - "--accesslog.format=json"
  - "--log.level=DEBUG"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.entryPoint=metrics"
  - "--entryPoints.metrics.address=:8082"

deployment:
  replicas: 3
  podAnnotations: 
    prometheus.io/port: '8082'
    prometheus.io/scrape: 'true'